### ISSUE TITLE
Menu does not show on blog after menu is created

### ISSUE THREAD

**Issue by jkishner** [scripting/1999-project#2] opened 2016-04-07 19:56 UTC
I was able to edit my menubar in the dialog box and save it.

![screen shot 2016-04-07 at 3 54 23 pm](https://cloud.githubusercontent.com/assets/1745919/14364919/1301a704-fcd9-11e5-8462-49238bfae3cb.png)

Yet I do not see the changes on my blog.

![screen shot 2016-04-07 at 3 55 09 pm](https://cloud.githubusercontent.com/assets/1745919/14364935/2cc5a03c-fcd9-11e5-8be9-f3c6a0f19421.png)

fwiw I am browsing the web behind a corporate firewall, and [my blog](http://1999.jeffreykishner.com/users/kishner/) is running on port 80.

**Comment by scripting** [comment] 2016-04-07 21:03
This might be caused by the fact that there are no docs yet.

Anyway -- it's not clear from your screen shot what you expected to happen, but that example didn't work on my machine either, nor should it.

Here's what I did:
1. On a fresh site, I edited the menu bar to add a Test menu, with a single sub-item pointing to my home page. (Screen shot below.)
2. I edited and saved one of the posts on my blog.
3. Viewed the story page for the post. 
4. The menu was there.

Here's the screen shot.,

![image](https://cloud.githubusercontent.com/assets/1686843/14366819/9aa5f8f0-fce2-11e5-8a04-7aaf094ef7e8.png)

**Comment by jkishner** [comment] 2016-04-07 21:10
I see. top level cannot be a link?

**Comment by scripting** [comment] 2016-04-07 21:11
Not as it's currently implemented. 

What would you expect it to do?

**Comment by scripting** [comment] 2016-04-07 21:12
Also, can you confirm that you're able to use it now, or not -- as the case may be. I'd like to close this issue if it is indeed closed.

**Comment by jkishner** [comment] 2016-04-07 21:22
you can close the ticket. it works.

I expected a top level node to be linkable, because that's the way it works
in the Fargo blog, e.g., see "About Me" at http://blog.jeffreykishner.com

**Comment by scripting** [comment] 2016-04-07 21:29
You know, even though I wrote that part of Fargo, you just surprised me with that. I never would have guessed it works that way. I could probably make this work that way too. But I'll close this issue which was more basic. Thanks for staying with this.

**Closed as completed by scripting** 2016-04-07 21:29 UTC
