### ISSUE TITLE
Changes in settings ignoring changes to templates

### ISSUE THREAD

**Issue by stoppableforce** [scripting/1999-project#6] opened 2016-04-12 16:41 UTC
1999 Version: 0.88i.

**How to reproduce:**
1. Make a change to your template using Main > Edit Template. In this case, I added a style link to a Google Font, and a CSS rule to change the font of a specific span.
2. Republish all pages. Visit front page of site. See new font in place.
3. Make a change to the blog's settings. In my case, I added a copyright.
4. Republish all pages. Visit front page of site. Site has reverted to old font.

**Workaround:**
1. In 1999, click Main > Edit Template. Click "OK" without changing anything.
2. Republish all pages. Visit front page of site. New font is in place, as is settings change.

**Comment by scripting** [comment] 2016-04-12 17:36
Thanks for the very good report.

I can reproduce it, and looking at the code I see exactly what the problem is.

I want to think a bit before I fix it, but it won't be hard to fix.

Thanks again.

**Comment by scripting** [comment] 2016-04-12 21:21
I believe this is fixed in v0.88j.

Just repeat the steps in your report, you shouldn't need the workaround.

Let me know if it works.

**Comment by stoppableforce** [comment] 2016-04-12 21:28
Looks like the fix was good - made a change to my template, republished, saw the change. Made a change to my settings, republished, saw both the template change and the settings change.

**Comment by scripting** [comment] 2016-04-12 21:35
Awesome. Very happy to have fixed this one. It was the source of a lot of misery. Thanks again! :-)

**Closed as completed by scripting** 2016-04-12 21:35 UTC
