### ISSUE TITLE
Losing edits when I scroll down the page

### ISSUE THREAD

**Issue by kenbooth** [scripting/1999-project#13] opened 2016-04-27 15:53 UTC
I was editing a post that had previously been saved. I wanted to add a link from a previous posts, so I scrolled down the page to copy it and when I scrolled back to the top of the page all of my edits were gone and the post had reverted to the previous saved version.

I was able to repeat this problem consistently and had no problem repeating it after refreshing the browser.

I am running Google Chrome 50.0.2661.86 on a Mac OS X El Capitan 10.11.4.

**Comment by scripting** [comment] 2016-04-27 16:07
First, it's good that it's repeatable.

Now I need the exact steps to make it repeat, because it isn't clear from the description what you did.

Not doubting that something went wrong, but I need to know how to make it happen here.

**Comment by kenbooth** [comment] 2016-04-27 16:14
Step 1: Create a post with any text and save
Step 2: Click to edit the post and type some new text at the end of the existing post.
Step 3: Scroll down the browser page until the opened edit box scrolls off of the top of the page.

Before I can scroll all the way to the bottom of the page it will jump back to the top and the new text I've added will be gone.

I hope this is more clear.

**Comment by scripting** [comment] 2016-04-27 16:17
Yes it is more clear, and I can reproduce here. 

I want to give this some thought before deciding what to do..

Thank you.

**Comment by scripting** [comment] 2016-04-27 17:56
I believe I understand what the problem is. We have an "infinite scroll" feature -- it automatically loads posts that are scrolled off the bottom when you reach the bottom. That's not taking into account the possibility that you're editing. I'm not closing this yet because I still have to do a code review to be sure that's the issue.

**Comment by scripting** [comment] 2016-04-27 22:13
This should be fixed in v0.88u. Please verify.

**Closed as completed by scripting** 2016-04-27 22:13 UTC

**Comment by kenbooth** [comment] 2016-04-27 22:54
Yes, fixed. I no longer see the problem.
